services: 
  zoo1: 
    image: zookeeper:3.4 
    restart: always 
    container_name: zoo1 
    ports: 
      - 2184:2181 
    environment: 
      ZOO_MY_ID: 1 
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 

  zoo2: 
    image: zookeeper:3.4 
    restart: always 
    container_name: zoo2 
    ports: 
      - 2185:2181 
    environment: 
      ZOO_MY_ID: 2 
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888 

  zoo3: 
    image: zookeeper:3.4 
    restart: always 
    container_name: zoo3 
    ports: 
      - 2186:2181 
    environment: 
      ZOO_MY_ID: 3 
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888 

  kafka1: 
    image: wurstmeister/kafka:2.12-2.4.1 
    restart: always 
    container_name: kafka1 
    privileged: true 
    ports: 
      - 19092:19092
    environment: 
      KAFKA_LISTENERS: PLAINTEXT://kafka1:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092
      KAFKA_ADVERTISED_PORT: 9092 
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181 
    depends_on: 
      - zoo1 
      - zoo2 
      - zoo3 

  kafka2: 
    image: wurstmeister/kafka:2.12-2.4.1 
    restart: always 
    container_name: kafka2 
    privileged: true 
    ports: 
      - 29092:29092
    environment: 
      KAFKA_LISTENERS: PLAINTEXT://kafka2:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092
      KAFKA_ADVERTISED_PORT: 9093 
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181 
    depends_on: 
      - zoo1 
      - zoo2 
      - zoo3 

  kafka3: 
    image: wurstmeister/kafka:2.12-2.4.1 
    restart: always 
    container_name: kafka3 
    privileged: true 
    ports: 
      - 39092:39092
    environment: 
      KAFKA_LISTENERS: PLAINTEXT://kafka3:39092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:39092
      KAFKA_ADVERTISED_PORT: 9094 
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181 
    depends_on: 
      - zoo1 
      - zoo2 
      - zoo3 
