services:
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    restart: always
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
     - "9091:9000"
   # links:      # 连接本compose文件创建的container
   #  - kafka1
   #  - kafka2
   #  - kafka3
   # external_links:  # 连接本compose文件以外的container
   #  - zoo1
   #  - zoo2
   #  - zoo3
    environment:
     ZK_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181
     KAFKA_BROKERS: kafka1:9092,kafka2:9093,kafka3:9094
     APPLICATION_SECRET: letmein
     KM_ARGS: -Djava.net.preferIPv4Stack=true
    networks:
     kafka:
      ipv4_address: 172.30.0.17

networks:
  kafka:
    external:
      name: kafka
