services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g:latest
    container_name: oracle
    restart: always
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      ORACLE_ALLOW_REMOTE: true
      ORACLE_ENABLE_XDB: true
    volumes:
      - ./data:/oradata
