services:
  keycloak:
    image: jboss/keycloak
    restart: always
    container_name: keycloak
    ports:
      - 8080:8080
      - 8082:8082
      - 9092:9092
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin