services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.0.0
    restart: always
    container_name: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka1-test:
    image: confluentinc/cp-kafka:7.0.0
    restart: always
    container_name: kafka1
    privileged: true
    depends_on:
      - zoo1
    ports:
      - 19092:19092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka1:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

