services:
  splunk:
    image: splunk/splunk:latest
    restart: always
    container_name: splunk
    ports:
      - 8000:8000
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: password