services:
  my_kdc:
    build: .
    container_name: my_kdc
    stdin_open: true
    tty: true
    privileged : true
    command: init
    ports:
      - 88:88
      - 749:749
      - 750:750
    volumes:
      - ./conf/kdc.conf:/var/kerberos/krb5kdc/kdc.conf
      - ./conf/krb5.conf:/etc/krb5.conf
      - ./conf/hosts:/etc/hosts
      - ./conf/kadm5.acl:/var/kerberos/krb5kdc/kadm5.acl
      - ./keytab:/keytab/