services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html

