services:
  jenkins:
    image: openjdk:11
    # restart: always
    container_name: jenkins
    user: root
    ports:
      - 8080:8080
    volumes:
      - ./jenkins.war:/app/jenkins.war
      - ./data:/root/.jenkins
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    command: java -Djava.awt.headless=true -Dhudson.model.DownloadService.noSignatureCheck=true -jar /app/jenkins.war