version: '2'

services:
  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    depends_on:
      - namenode
      - datanode
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./conf/hive-site.xml:/spark/conf/hive-site.xml:ro
      - ./conf/hosts:/etc/hosts
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

  spark-worker-1:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./conf/hive-site.xml:/spark/conf/hive-site.xml:ro
      - ./conf/hosts:/etc/hosts
      - ./demo/demo.py:/demo.py
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000