services:
  ldap:
    image: osixia/openldap:latest
    restart: always
    container_name: ldap
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANISATION: example
      LDAP_DOMAIN: example.com
      LDAP_ADMIN_PASSWORD: 123456

  ldapadmin:
    image: osixia/phpldapadmin:latest
    restart: always
    container_name: ldapadmin
    depends_on:
      - ldap
    ports:
      - 8080:80
    environment:
      PHPLDAPADMIN_HTTPS: 'false'
      PHPLDAPADMIN_LDAP_HOSTS: ldap