services:
  portainer:
    image: portainer/portainer-ce:2.11.0
    restart: always
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data: