services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU11-ubuntu-20.04
    restart: always
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: '!SqlServer2'