services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
      - ./data:/data:rw

