services:
  zoo1:
    image: zookeeper:3.4
    restart: "no"
    container_name: zoo1
    ports:
      - 2181:2181
    volumes:
      - "./zkcluster/zoo1/data:/data"
      - "./zkcluster/zoo1/datalog:/datalog"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888

  kafka1:
    image: wurstmeister/kafka:2.13-2.8.1
    restart: "no"
    container_name: kafka1
    privileged: true
    ports:
      - 19092:19092
      - 19093:19093
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka1:19092,SSL://kafka1:19093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092,SSL://kafka1:19093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_SSL_KEYSTORE_LOCATION: /secrets/kafka.broker1.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: confluent
      KAFKA_SSL_KEY_PASSWORD: confluent
      KAFKA_SSL_TRUSTSTORE_LOCATION: /secrets/kafka.broker1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: confluent
      KAFKA_SSL_CLIENT_AUTH: none
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
    volumes:
      - ./kafkaCluster/kafka1/logs:/kafka
      - ./secrets:/secrets
    depends_on:
      - zoo1

  kafka2:
    image: wurstmeister/kafka:2.13-2.8.1
    restart: "no"
    container_name: kafka2
    privileged: true
    ports:
      - 29092:29092
      - 29093:29093
    environment:
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka2:29092,SSL://kafka2:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092,SSL://kafka2:29093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_SSL_KEYSTORE_LOCATION: /secrets/kafka.broker1.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: confluent
      KAFKA_SSL_KEY_PASSWORD: confluent
      KAFKA_SSL_TRUSTSTORE_LOCATION: /secrets/kafka.broker1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: confluent
      KAFKA_SSL_CLIENT_AUTH: none
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
    volumes:
      - ./kafkaCluster/kafka2/logs:/kafka
      - ./secrets:/secrets
    depends_on:
      - zoo1

  kafka3:
    image: wurstmeister/kafka:2.13-2.8.1
    restart: "no"
    container_name: kafka3
    privileged: true
    ports:
      - 39092:39092
      - 39093:39093
    environment:
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka3:39092,SSL://kafka3:39093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:39092,SSL://kafka3:39093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_SSL_KEYSTORE_LOCATION: /secrets/kafka.broker1.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: confluent
      KAFKA_SSL_KEY_PASSWORD: confluent
      KAFKA_SSL_TRUSTSTORE_LOCATION: /secrets/kafka.broker1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: confluent
      KAFKA_SSL_CLIENT_AUTH: none
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
    volumes:
      - ./kafkaCluster/kafka3/logs:/kafka
      - ./secrets:/secrets
    depends_on:
      - zoo1
